/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type PartnerNote = {
  _type: "partnerNote";
  title?: string;
  description?: string;
  tags?: Array<string>;
  confidence?: "certain" | "likely" | "needs-check";
  onboardingQuestionId?: string;
  mirroredFromNoteKey?: string;
  isShared?: boolean;
  corrections?: Array<{
    authorId?: string;
    authorName?: string;
    text?: string;
    createdAt?: string;
    _type: "noteCorrection";
    _key: string;
  }>;
  createdAt?: string;
  updatedAt?: string;
};

export type CalendarEvent = {
  _type: "calendarEvent";
  type?: "important" | "intimate" | "daily";
  title?: string;
  date?: string;
  time?: string;
  durationMinutes?: number;
  isRecurringYearly?: boolean;
  mood?: "great" | "good" | "neutral" | "sad" | "upset" | "romantic" | "angry";
  activities?: Array<string>;
  initiatedBy?: "me" | "partner" | "mutual";
  selfFinished?: boolean;
  partnerFinished?: boolean;
  protectionUsed?: boolean;
  protectionType?:
    "condom" | "dental_dam" | "birth_control_pill" | "iud" | "other";
  rating?: number;
  highlights?: Array<string>;
  note?: string;
  createdAt?: string;
};

export type UserReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "user";
};

export type Message = {
  _type: "message";
  text?: string;
  createdAt?: string;
  isShown?: boolean;
  userName?: string;
  category?: "unknown" | "daily" | "extra";
  specificDate?: string;
  like?: boolean;
  shownAt?: string;
  shownBy?: UserReference;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  name?: string;
  login?: string;
  password?: string;
  role?: "user" | "admin";
  partnerIdToSend?: string;
  phone?: string;
  dayMessageLimit?: number;
  partnerIdToReceiveFrom?: string;
  messages?: Array<
    {
      _key: string;
    } & Message
  >;
  calendarEvents?: Array<
    {
      _key: string;
    } & CalendarEvent
  >;
  partnerNotes?: Array<
    {
      _key: string;
    } & PartnerNote
  >;
  compatibilityAnalysis?: {
    text?: string;
    generatedAt?: string;
    ownNotesCount?: number;
    partnerNotesCount?: number;
  };
  dismissedNoteSuggestionKeys?: Array<string>;
  geminiApiKey?: string;
  partnerInfo?: string;
  aiScanLanguage?: "uk" | "en" | "ru" | "pl" | "de" | "es" | "fr";
  localScanLanguage?: "uk" | "en" | "ru" | "pl" | "de" | "es" | "fr";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | PartnerNote
  | CalendarEvent
  | UserReference
  | Message
  | SanityImageAssetReference
  | User
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;
